version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
      TZ: 'America/Mexico_city'
    volumes: 
      - "$PWD/postgres:/var/lib/postgresql/data/"
    networks:
      - postgre_net
  pg_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 8080:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks: 
      - red
networks:
  postgre_net: