version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql
    command:
      - --default-time-zone=America/Mexico_city
      - --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: general
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_PASSWORD: root1234,
      TZ: America/Mexico_city
    volumes:
      - $PWD/mysql_data:/var/lib/mysql
    networks:
      - db_red
networks:
  db_red:


